# Generated by Django 5.2.8 on 2025-11-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbound_hospital',
            name='calling_process',
            field=models.CharField(blank=True, choices=[('not_happened', 'NOT HAPPENED'), ('connected', 'CONNECTED'), ('not_connected', 'NOT CONNECTED')], default='not_happened', max_length=30, null=True),
        ),
    ]
