# Generated by Django 5.2.11 on 2026-03-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor_model",
            name="availability",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="doctor_model",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="hospital_model",
            name="pharmacy_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="hospital_model",
            name="reception_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="medivoicesession",
            name="diagnosis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medivoicesession",
            name="medicines",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medivoicesession",
            name="revisit_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medivoicesession",
            name="revisit_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="textmodel",
            name="media_url",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
