# Generated by Django 5.2.8 on 2025-12-22 16:21

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_outbound_hospital_calling_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbound_Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('vapi_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(blank=True, max_length=1000, null=True)),
                ('endedReason', models.CharField(blank=True, max_length=1000, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message_s3_link', models.CharField(blank=True, max_length=10000, null=True)),
                ('audio_link', models.CharField(blank=True, max_length=10000, null=True)),
                ('task_id', models.CharField(blank=True, max_length=10000, null=True)),
                ('task_id_process', models.CharField(blank=True, max_length=10000, null=True)),
                ('calling_process', models.CharField(blank=True, choices=[('not_happened', 'NOT HAPPENED'), ('connected', 'CONNECTED'), ('not_connected', 'NOT CONNECTED')], default='not_happened', max_length=30, null=True)),
                ('from_phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('to_phone_numnber', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
