# Generated by Django 5.2.8 on 2025-12-30 17:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_inbound_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallFeedbackModel_inbound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_status', models.CharField(choices=[('connected', 'Connected'), ('not_connected', 'Not Connected')], max_length=20)),
                ('call_outcome', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('escalated', 'Escalated'), ('no_feedback', 'No Feedback')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('community_added', models.BooleanField(default=False)),
                ('revisit_encouraged', models.BooleanField(default=False)),
                ('escalation_required', models.BooleanField(default=False)),
                ('call_duration', models.CharField(blank=True, null=True)),
                ('called_by', models.CharField(blank=True, max_length=255, null=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.inbound_hospital')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityEngagementModel_inbound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engagement_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('poll_participation', 'Poll Participation'), ('like', 'Like'), ('share', 'Share')], max_length=20)),
                ('engagement_date', models.DateField(default=django.utils.timezone.localdate)),
                ('department', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.inbound_hospital')),
            ],
        ),
        migrations.CreateModel(
            name='EscalationModel_inbound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('department', models.TextField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.inbound_hospital')),
            ],
        ),
    ]
