# Generated by Django 5.2.8 on 2025-12-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_callfeedbackmodel_inbound_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbound_hospital',
            name='department',
            field=models.CharField(blank=True, default='N/A', max_length=255, null=True),
        ),
    ]
