# Generated by Django 5.2.11 on 2026-02-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_inbound_hospital_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inbound_hospital",
            name="calling_process",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_happened", "NOT HAPPENED"),
                    ("connected", "CONNECTED"),
                    ("not_connected", "NOT CONNECTED"),
                    ("in_progress", "IN PROGRESS"),
                ],
                default="not_happened",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="outbound_hospital",
            name="calling_process",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_happened", "NOT HAPPENED"),
                    ("connected", "CONNECTED"),
                    ("not_connected", "NOT CONNECTED"),
                    ("in_progress", "IN PROGRESS"),
                ],
                default="not_happened",
                max_length=30,
                null=True,
            ),
        ),
    ]
